baseURL = "http://example.org/"
languageCode = "en-us"
title = "Haben Amare"
theme = "personal-website-theme"

enableGitInfo = true

[markup]
  [markup.highlight]
    style = "trac"

[params]
  fullName = "Haben Amare"

  [[params.navItems]]
    title = "Home"
    path = "/"

  [[params.navItems]]
    title = "Articles"
    path = "/articles"

  [[params.navItems]]
    title = "Guides"
    path = "/guides"

  [[params.navItems]]
    title = "Projects"
    path = "/projects"

  [[params.navItems]]
    title = "About"
    path = "/about"
