baseURL = "http://example.org/"
languageCode = "en-us"
title = "Haben Amare"
theme = "custom-hugo-theme"

[params]
  fullName = "Haben Amare"

  [[params.navItems]]
    title = "Home"
    path = "/"

  [[params.navItems]]
    title = "Guides"
    path = "/guides"
